// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import {ReentrancyGuard} from "@openzeppelin/contracts/utils/ReentrancyGuard.sol";
import {Ownable} from "@openzeppelin/contracts/access/Ownable.sol";

/// @title RitualTreasury
/// @notice Collects every action fee generated by RitualSocial and routes
///         it toward creator rewards, community campaigns, governance,
///         events, and direct tipping — exactly as described in the spec.
///         All disbursement is on-chain and verifiable on Ritual Explorer.
contract RitualTreasury is ReentrancyGuard, Ownable {
    enum Category {
        CreatorReward,
        CommunityCampaign,
        Governance,
        Event,
        Tipping
    }

    error InsufficientBalance(uint256 requested, uint256 available);
    error ZeroAddress();
    error ZeroAmount();

    /// @notice Only this contract (RitualSocial) may call `deposit`.
    address public socialContract;

    uint256 public totalCollected;
    mapping(Category => uint256) public categoryBalance;

    event Deposited(address indexed payer, uint256 amount, uint256 timestamp);
    event Disbursed(Category indexed category, address indexed to, uint256 amount, string reason, uint256 timestamp);
    event Tipped(address indexed from, address indexed to, uint256 amount, uint256 timestamp);
    event SocialContractUpdated(address oldContract, address newContract);

    modifier onlySocialContract() {
        require(msg.sender == socialContract, "RitualTreasury: caller is not RitualSocial");
        _;
    }

    constructor(address initialOwner) Ownable(initialOwner) {}

    /// @notice Wires up the RitualSocial contract address post-deployment
    ///         (avoids a circular constructor dependency between the two).
    function setSocialContract(address newSocialContract) external onlyOwner {
        if (newSocialContract == address(0)) revert ZeroAddress();
        emit SocialContractUpdated(socialContract, newSocialContract);
        socialContract = newSocialContract;
    }

    /// @notice Called by RitualSocial for every fee-bearing action. Fees are
    ///         split evenly across the five allocation categories; adjust
    ///         `_splitBps` if your DAO governance decides on a different mix.
    function deposit(address payer) external payable onlySocialContract {
        if (msg.value == 0) revert ZeroAmount();
        totalCollected += msg.value;

        uint256 share = msg.value / 5;
        uint256 remainder = msg.value - (share * 4);

        categoryBalance[Category.CreatorReward] += share;
        categoryBalance[Category.CommunityCampaign] += share;
        categoryBalance[Category.Governance] += share;
        categoryBalance[Category.Event] += share;
        categoryBalance[Category.Tipping] += remainder; // absorbs rounding dust

        emit Deposited(payer, msg.value, block.timestamp);
    }

    /// @notice Direct wallet-to-creator tip, bypassing category accounting.
    function tip(address creator) external payable nonReentrant {
        if (creator == address(0)) revert ZeroAddress();
        if (msg.value == 0) revert ZeroAmount();

        (bool ok, ) = payable(creator).call{value: msg.value}("");
        require(ok, "RitualTreasury: tip transfer failed");

        emit Tipped(msg.sender, creator, msg.value, block.timestamp);
    }

    /// @notice Governance/multisig-gated disbursement from a category pool.
    function disburse(Category category, address to, uint256 amount, string calldata reason)
        external
        onlyOwner
        nonReentrant
    {
        if (to == address(0)) revert ZeroAddress();
        uint256 available = categoryBalance[category];
        if (amount > available) revert InsufficientBalance(amount, available);

        categoryBalance[category] = available - amount;
        (bool ok, ) = payable(to).call{value: amount}("");
        require(ok, "RitualTreasury: disbursement failed");

        emit Disbursed(category, to, amount, reason, block.timestamp);
    }

    function balanceOf(Category category) external view returns (uint256) {
        return categoryBalance[category];
    }

    receive() external payable {
        totalCollected += msg.value;
        categoryBalance[Category.CommunityCampaign] += msg.value;
        emit Deposited(msg.sender, msg.value, block.timestamp);
    }
}
